minio:
  url: http://175.178.50.99:9000
  accessKey: Nvveu5qsGrIZMo2JKPRh
  secretKey: zumDuxs3C4XOLUG1tJjQlJP6KbPLHcLMWkEL0Rmt

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'LeviMySQL!@#456'
    url: jdbc:mysql://175.178.50.99:13306/file_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB